<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/jquery-1.8.3.min.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/jquery-ui-1.10.2.custom.min.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/Kendo Q1 2014/kendo.web.v2014.1.318.508.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/html5shiv.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/selectivizr-min.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/script.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/modernizr-2.6.2.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/AjaxLogin.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/jquery.ba-bbq.min.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/jquery.dataTables.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/ltss.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/ltss.kendo.extensions.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/jquery.dataTables.rowGrouping.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/jquery-textFill-0.1.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/jquery.fancybox.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/ltss.overlay.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/ltss.panelBar.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/menu.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/jquery.validate.min.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/jquery.blockUI.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/jquery.cycle.all.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/jquery.list.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/jquery.dotdotdot-1.5.1.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/jquery.mousewheel.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/jquery.mwheelIntent.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/jquery.jscrollpane.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/scroll-startstop.events.jquery.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/html2canvas.min.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/jquery.plugin.html2canvas.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/ltss.leftnavigation.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/jquery.qtip.min.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/knockout-2.1.0.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/jSignature.min.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/ckeditor/adapters/jquery.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/ckeditor/ckeditor-toolbar-config.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>application/Scripts/localstoragedb.min.js"></script>